name: Modrinth Publish
on:
  release:
    types: [ prereleased, released ]
jobs:
  build:
    env:
      CHANGELOG: ${{ github.event.release.body }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Publish with Gradle to Modrinth
        run: ./gradlew modrinth